"""Tests for the post-quantum (PQ) readiness rule pack and summary.

Same style as test_code_scanner: build a tiny tree under tmp_path,
scan with the real orchestrator, assert the right pqc.* rules fire —
and, just as important, that hybrid-aware lines do NOT fire.
"""

from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from app.cli import _scan_result_to_payload
from app.core.code_scanner import (
    Confidence,
    Finding,
    ScanRequest,
    ScanTargetType,
    Severity,
    scan_target,
)
from app.core.code_scanner.pq_readiness import summarize_pq_readiness
from app.core.code_scanner.sarif import to_sarif
from app.main import app

client = TestClient(app)


def _write(tmp_path: Path, relative: str, content: str) -> None:
    target = tmp_path / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def _scan(tmp_path: Path):
    return scan_target(ScanRequest(target=str(tmp_path), target_type=ScanTargetType.PATH))


def _rule_ids(result) -> set[str]:
    return {f.rule_id for f in result.findings}


# ---------- individual rules --------------------------------------------


def test_flags_rsa_keygen_python(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/keys.py",
        "from cryptography.hazmat.primitives.asymmetric import rsa\n"
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    )
    assert "pqc.rsa-in-use" in _rule_ids(_scan(tmp_path))


def test_flags_rsa_keygen_java_and_openssl(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/Keys.java",
        'KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");\n',
    )
    _write(tmp_path, "scripts/gen.sh", "openssl genrsa -out server.key 2048\n")
    result = _scan(tmp_path)
    rsa_findings = [f for f in result.findings if f.rule_id == "pqc.rsa-in-use"]
    assert {f.file_path for f in rsa_findings} == {"src/Keys.java", "scripts/gen.sh"}


def test_flags_classical_key_exchange_go(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/kex.go",
        "priv, _ := ecdh.P256().GenerateKey(rand.Reader)\n"
        "curve := ecdh.X25519()\n",
    )
    assert "pqc.classical-key-exchange" in _rule_ids(_scan(tmp_path))


def test_hybrid_kex_line_is_not_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/kex_hybrid.go",
        "shared := ecdh.X25519() // combined with MLKEM768 hybrid share\n",
    )
    assert "pqc.classical-key-exchange" not in _rule_ids(_scan(tmp_path))


def test_flags_pinned_classical_groups_nginx(tmp_path: Path) -> None:
    _write(tmp_path, "conf/nginx.conf", "ssl_ecdh_curve X25519:prime256v1;\n")
    assert "pqc.classical-kex-pinned-config" in _rule_ids(_scan(tmp_path))


def test_pinned_groups_with_hybrid_not_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "conf/sshd_config",
        "KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256\n",
    )
    _write(tmp_path, "conf/nginx-pq.conf", "ssl_ecdh_curve X25519MLKEM768:X25519;\n")
    assert "pqc.classical-kex-pinned-config" not in _rule_ids(_scan(tmp_path))


def test_multiline_hybrid_go_config_not_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/tls.go",
        "cfg := &tls.Config{\n"
        "\tCurvePreferences: []tls.CurveID{\n"
        "\t\ttls.X25519MLKEM768,\n"
        "\t\ttls.X25519,\n"
        "\t},\n"
        "}\n",
    )
    assert "pqc.classical-kex-pinned-config" not in _rule_ids(_scan(tmp_path))


def test_multiline_classical_only_go_config_is_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/tls.go",
        "cfg := &tls.Config{\n"
        "\tCurvePreferences: []tls.CurveID{\n"
        "\t\ttls.CurveP256,\n"
        "\t},\n"
        "}\n",
    )
    assert "pqc.classical-kex-pinned-config" in _rule_ids(_scan(tmp_path))


def test_autogenerated_comment_does_not_suppress_pin(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "conf/nginx.conf",
        "ssl_ecdh_curve prime256v1; # autogenerated by deploy tooling\n",
    )
    assert "pqc.classical-kex-pinned-config" in _rule_ids(_scan(tmp_path))


def test_flags_apache_and_equals_kex_spellings(tmp_path: Path) -> None:
    _write(tmp_path, "conf/httpd.conf", "SSLOpenSSLConfCmd Groups X25519:secp384r1\n")
    _write(tmp_path, "conf/ssh_config", "KexAlgorithms=curve25519-sha256,ecdh-sha2-nistp256\n")
    result = _scan(tmp_path)
    pinned = [f for f in result.findings if f.rule_id == "pqc.classical-kex-pinned-config"]
    assert {f.file_path for f in pinned} == {"conf/httpd.conf", "conf/ssh_config"}


def test_flags_classical_signature_java(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/Sig.java",
        'Signature sig = Signature.getInstance("SHA256withECDSA");\n',
    )
    assert "pqc.classical-signature" in _rule_ids(_scan(tmp_path))


def test_flags_jwt_classical_alg(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/token.py",
        'token = jwt.encode(payload, key, algorithm="RS256")\n',
    )
    assert "pqc.jwt-classical-alg" in _rule_ids(_scan(tmp_path))


def test_flags_weak_rsa_keysize(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/legacy.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=1024)\n",
    )
    assert "pqc.weak-asymmetric-keysize" in _rule_ids(_scan(tmp_path))


def test_flags_weak_keysize_java_two_line_idiom(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/Keys.java",
        'KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");\n'
        "kpg.initialize(1024, new SecureRandom());\n",
    )
    assert "pqc.weak-asymmetric-keysize" in _rule_ids(_scan(tmp_path))


def test_flags_weak_dh_and_dsa_param_generation(tmp_path: Path) -> None:
    _write(tmp_path, "scripts/dh.sh", "openssl dhparam -out dhparams.pem 1024\n")
    _write(tmp_path, "scripts/dsa.sh", "openssl dsaparam -genkey 1024\n")
    result = _scan(tmp_path)
    weak = [f for f in result.findings if f.rule_id == "pqc.weak-asymmetric-keysize"]
    assert {f.file_path for f in weak} == {"scripts/dh.sh", "scripts/dsa.sh"}


def test_flags_aes128_selection(tmp_path: Path) -> None:
    _write(tmp_path, "conf/tls.conf", "ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256;\n")
    assert "pqc.small-symmetric-key" in _rule_ids(_scan(tmp_path))


def test_flags_aes128_java_two_line_idiom(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/Sym.java",
        'KeyGenerator kgen = KeyGenerator.getInstance("AES");\nkgen.init(128);\n',
    )
    assert "pqc.small-symmetric-key" in _rule_ids(_scan(tmp_path))


def test_flags_classical_signature_java_case_variants(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/Sig2.java",
        'Signature a = Signature.getInstance("SHA256WithRSA");\n'
        'Signature b = Signature.getInstance("RSASSA-PSS");\n',
    )
    sig = [f for f in _scan(tmp_path).findings if f.rule_id == "pqc.classical-signature"]
    assert len(sig) == 2


def test_flags_jwt_unquoted_alg_and_allow_list(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/jose.js",
        "const t = await new jose.SignJWT(payload).setProtectedHeader({ alg: 'ES256' }).sign(key);\n",
    )
    _write(
        tmp_path,
        "src/verify.py",
        'claims = jwt.decode(token, key, algorithms=["HS256", "RS256"])\n',
    )
    result = _scan(tmp_path)
    jwt_findings = [f for f in result.findings if f.rule_id == "pqc.jwt-classical-alg"]
    assert {f.file_path for f in jwt_findings} == {"src/jose.js", "src/verify.py"}


def test_ssh_keygen_rsa_is_signature_not_hndl(tmp_path: Path) -> None:
    _write(tmp_path, "scripts/keys.sh", "ssh-keygen -t rsa -b 4096 -f id_rsa\n")
    result = _scan(tmp_path)
    ids = _rule_ids(result)
    assert "pqc.classical-signature" in ids
    assert "pqc.rsa-in-use" not in ids
    assert result.pq_readiness["hndl_exposure"] == 0


def test_flags_pqc_adoption(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/pq.py",
        "import oqs\n"
        'kem = oqs.KeyEncapsulation("ML-KEM-768")\n',
    )
    assert "pqc.pqc-in-use" in _rule_ids(_scan(tmp_path))


def test_flags_weak_pqc_parameter_set(tmp_path: Path) -> None:
    _write(tmp_path, "src/pq_small.py", 'kem = oqs.KeyEncapsulation("Kyber512")\n')
    ids = _rule_ids(_scan(tmp_path))
    assert "pqc.weak-pqc-parameter-set" in ids
    assert "pqc.pqc-in-use" in ids


def test_camelcase_identifiers_do_not_fire_pqc_in_use(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/app.js",
        "const xmlDsaValidator = loadXmlDsaSchema();\n"
        "const htmlKemNode = document.querySelector('#kem');\n"
        "import { KyberNetworkProxy } from '@kyber/contracts';\n",
    )
    result = _scan(tmp_path)
    assert "pqc.pqc-in-use" not in _rule_ids(result)
    assert result.pq_readiness["status"] == "no_crypto_detected"


def test_textbook_modern_crypto_scores_low_risk(tmp_path: Path) -> None:
    # Today-standard RSA-4096 + X25519 is PQ *inventory*, not suspicious
    # code — the composite score must not jump into moderate/high bands.
    _write(
        tmp_path,
        "src/keymgmt.py",
        "transport = rsa.generate_private_key(public_exponent=65537, key_size=4096)\n"
        "ephemeral = X25519PrivateKey.generate()\n",
    )
    result = _scan(tmp_path)
    assert result.risk == "low"
    assert result.score < 0.30


def test_cache_key_size_setting_is_not_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/cache.py",
        "max_key_size = 1024  # cache entries larger than this are rejected\n",
    )
    assert "pqc.weak-asymmetric-keysize" not in _rule_ids(_scan(tmp_path))


def test_ssl_ecdh_curve_auto_is_not_flagged(tmp_path: Path) -> None:
    _write(tmp_path, "conf/nginx.conf", "ssl_ecdh_curve auto;\n")
    assert "pqc.classical-kex-pinned-config" not in _rule_ids(_scan(tmp_path))


def test_plain_code_has_no_pqc_findings(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/clean.py",
        "def add(a, b):\n    return a + b\n\nGROUPS = ['admin', 'users']\n",
    )
    result = _scan(tmp_path)
    assert not any(f.rule_id.startswith("pqc.") for f in result.findings)
    assert result.pq_readiness["status"] == "no_crypto_detected"


# ---------- readiness summary -------------------------------------------


def test_pq_readiness_quantum_vulnerable(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/keys.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    )
    pq = _scan(tmp_path).pq_readiness
    assert pq["status"] == "quantum_vulnerable"
    assert pq["hndl_exposure"] >= 1
    assert pq["files_affected"] == 1


def test_pq_readiness_migration_in_progress(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/mixed.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n"
        'kem = oqs.KeyEncapsulation("ML-KEM-768")\n',
    )
    pq = _scan(tmp_path).pq_readiness
    assert pq["status"] == "migration_in_progress"
    assert pq["pqc_findings"] >= 1
    assert pq["classical_findings"] >= 1


def test_pq_readiness_pq_ready_with_weak_param_note(tmp_path: Path) -> None:
    _write(tmp_path, "src/pq.py", 'kem = oqs.KeyEncapsulation("ML-KEM-512")\n')
    pq = _scan(tmp_path).pq_readiness
    assert pq["status"] == "pq_ready"
    assert pq["weak_pqc_parameter_findings"] >= 1
    # Substring unique to the weak-param prepend, not the base pq_ready text.
    assert "upgrade those first" in pq["recommendation"]


def test_pq_readiness_aes128_only_is_not_pq_ready(tmp_path: Path) -> None:
    _write(tmp_path, "conf/tls.conf", "ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256;\n")
    pq = _scan(tmp_path).pq_readiness
    assert pq["status"] == "symmetric_margin_only"
    assert "AES-256" in pq["recommendation"]


def test_summarize_ignores_non_pqc_findings() -> None:
    assert summarize_pq_readiness([])["status"] == "no_crypto_detected"
    eval_finding = Finding(
        rule_id="py.eval-on-input",
        title="eval",
        description="",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        category="eval",
        file_path="src/danger.py",
        line_start=1,
        line_end=1,
        snippet="eval(x)",
    )
    pq = summarize_pq_readiness([eval_finding])
    assert pq["status"] == "no_crypto_detected"
    assert pq["families"] == {}


# ---------- surfaces ------------------------------------------------------


def test_api_scan_includes_pq_readiness(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/keys.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    )
    response = client.post(
        "/api/v1/scan-code",
        json={"target": str(tmp_path), "target_type": "path"},
    )
    assert response.status_code == 200
    body = response.json()
    assert body["pq_readiness"]["status"] == "quantum_vulnerable"


def test_cli_payload_includes_pq_readiness(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/keys.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    )
    payload = _scan_result_to_payload(_scan(tmp_path))
    assert payload["pq_readiness"]["status"] == "quantum_vulnerable"


def test_sarif_includes_pqc_rules(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "src/keys.py",
        "key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    )
    sarif = to_sarif(_scan(tmp_path))
    rule_ids = {rule["id"] for rule in sarif["runs"][0]["tool"]["driver"]["rules"]}
    assert "pqc.rsa-in-use" in rule_ids
